name: CI
on: [push, pull_request]

jobs:
  build-test:
    name: "Build & Test (${{ matrix.os }} / Java ${{ matrix.java }})"
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [17, 21]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - name: Build and test
        run: mvn -B -DskipTests=false verify

      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-${{ matrix.os }}-java${{ matrix.java }}
          path: target/surefire-reports

      - name: Upload JaCoCo reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-${{ matrix.os }}-java${{ matrix.java }}
          path: |
            target/site/jacoco
            target/jacoco.exec

      - name: SonarCloud analysis
        if: matrix.os == 'ubuntu-latest' && matrix.java == 17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar \
            -Dsonar.login=638d949c68941115dfe7a790184f847a660da45a \
            -Dsonar.organization=lichtiix \
            -Dsonar.projectKey=Lichtiix_cicd-BA-uebung01-Lichtenberger \
            -Dsonar.host.url=https://sonarcloud.io
